import { Order } from '@/types/order'

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    clientName: 'LabCorp',
    shipTo: '1901 S Alvernon Way, Tucson, AZ 85711',
    dateSubmitted: new Date('2026-02-08T14:30:00'),
    orderQty: 2,
    customerPO: 'PO-458912',
    shippingLabelCount: 2,
    returnLabelCount: 2,
    trfFormCount: 2,
    kitIdLabelCount: 2,
    patientLabelCount: 2,
    status: 'Approved',
    kitName: 'Colofit Kit',
    kitId: 3564567,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-002',
    clientName: 'LabCorp',
    shipTo: '20 Patriot Place, Foxborough, MA 02035',
    dateSubmitted: new Date('2026-02-07T09:15:00'),
    orderQty: 5,
    customerPO: 'PO-458913',
    shippingLabelCount: 5,
    returnLabelCount: 5,
    trfFormCount: 5,
    kitIdLabelCount: 5,
    patientLabelCount: 5,
    status: 'Approved',
    kitName: 'Adx Kit',
    kitId: 3564568,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-003',
    clientName: 'LabCorp',
    shipTo: '450 N Brand Blvd, Glendale, CA 91203',
    dateSubmitted: new Date('2026-02-07T11:00:00'),
    orderQty: 4,
    customerPO: 'PO-458920',
    shippingLabelCount: 4,
    returnLabelCount: 4,
    trfFormCount: 4,
    kitIdLabelCount: 4,
    patientLabelCount: 4,
    status: 'Approved',
    kitName: 'Colofit Kit',
    kitId: 3564575,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-004',
    clientName: 'LabCorp',
    shipTo: '1201 3rd Ave, Seattle, WA 98101',
    dateSubmitted: new Date('2026-02-06T16:45:00'),
    orderQty: 3,
    customerPO: 'PO-458914',
    shippingLabelCount: 3,
    returnLabelCount: 3,
    trfFormCount: 3,
    kitIdLabelCount: 3,
    patientLabelCount: 3,
    status: 'Approved',
    kitName: 'A1C Kit',
    kitId: 3564569,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-005',
    clientName: 'LabCorp',
    shipTo: '100 SE 2nd St, Miami, FL 33131',
    dateSubmitted: new Date('2026-02-05T11:20:00'),
    orderQty: 10,
    customerPO: 'PO-458915',
    shippingLabelCount: 10,
    returnLabelCount: 10,
    trfFormCount: 10,
    kitIdLabelCount: 10,
    patientLabelCount: 10,
    status: 'Approved',
    kitName: 'Kidney Combo Kit',
    kitId: 3564570,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-006',
    clientName: 'LabCorp',
    shipTo: '191 Peachtree St NE, Atlanta, GA 30303',
    dateSubmitted: new Date('2026-02-04T10:05:00'),
    orderQty: 48,
    customerPO: 'PO-458917',
    shippingLabelCount: 48,
    returnLabelCount: 48,
    trfFormCount: 48,
    kitIdLabelCount: 48,
    patientLabelCount: 48,
    status: 'Approved',
    kitName: 'Adx Kit',
    kitId: 3564572,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-007',
    clientName: 'LabCorp',
    shipTo: '1144 15th St, Denver, CO 80202',
    dateSubmitted: new Date('2026-02-03T13:10:00'),
    orderQty: 2,
    customerPO: 'PO-458916',
    shippingLabelCount: 2,
    returnLabelCount: 2,
    trfFormCount: 2,
    kitIdLabelCount: 2,
    patientLabelCount: 2,
    status: 'Approved',
    kitName: 'Colofit Kit',
    kitId: 3564571,
    isApprovedByLabcorp: true,
  },
  {
    id: 'ORD-008',
    clientName: 'LabCorp',
    shipTo: '2001 Ross Ave, Dallas, TX 75201',
    dateSubmitted: new Date('2026-02-01T08:00:00'),
    orderQty: 5,
    customerPO: 'PO-458919',
    shippingLabelCount: 5,
    returnLabelCount: 5,
    trfFormCount: 5,
    kitIdLabelCount: 5,
    patientLabelCount: 5,
    status: 'Approved',
    kitName: 'Kidney Combo Kit',
    kitId: 3564574,
    isApprovedByLabcorp: true,
  },
]

export function getOrdersByStatus(status: string): Order[] {
  if (status === 'all') return mockOrders
  return mockOrders.filter(order => order.status === status)
}

export function getOrderStatusCounts() {
  const counts: Record<string, number> = {
    Approved: 0,
    Inprocess: 0,
    Onhold: 0,
    'QC Failed': 0,
    Shipped: 0,
    Cancelled: 0,
  }

  mockOrders.forEach(order => {
    counts[order.status]++
  })

  return counts
}
